export enum FunctionalitiesClientsStatus {
  PENDING_PAYMENT = 'PENDING_PAYMENT',
  IN_PROGRESS = 'IN_PROGRESS',
  AWAITING_CLIENT = 'AWAITING_CLIENT',
  AWAITING_ADVISOR = 'AWAITING_ADVISOR',
  COMPLETED = 'COMPLETED',
  CANCELED = 'CANCELED',
  OVERDUE = 'OVERDUE',
}
